name: Build & Deploy Flutter Web

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter (stable pinned)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.22.2"

      - name: Doctor
        run: |
          flutter --version
          flutter doctor -v
          flutter config --enable-web

      - name: Pub Get
        run: flutter pub get

      - name: Build Web Release
        run: flutter build web --release --web-renderer html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages

